### ISSUE TITLE
Space travellers project

### ISSUE THREAD

**Issue by selma-belhadj** [selma-belhadj/space-travelers#25]
Hello, 
We are a group of 3
https://github.com/selma-belhadj/space-travelers/projects/1

**Comment by Whoistolu** [comment]
### Hi Team,
@selma-belhadj , @awais-amjed and @M0rrighan 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
